import { StyleSheet } from 'react-native';
import Theme from '../constants/Theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  scroll: { padding: Theme.spacing.md, paddingBottom: 80 },

  sectionCard: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.lg,
    marginBottom: Theme.spacing.md,
    ...Theme.shadow.xs,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: Theme.colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: Theme.spacing.md,
  },

  label: {
    fontSize: 11,
    fontWeight: '600',
    color: Theme.colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 6,
  },
  input: {
    backgroundColor: Theme.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.sm,
    paddingVertical: 11,
    paddingHorizontal: 13,
    fontSize: 14,
    color: Theme.colors.text,
  },
  inputHalf: { maxWidth: 130 },
  textArea: { height: 75, textAlignVertical: 'top' },

  pickerButton: {
    backgroundColor: Theme.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.sm,
    paddingVertical: 11,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickerButtonText: { fontSize: 14, color: Theme.colors.text },
  pickerButtonPlaceholder: { fontSize: 14, color: Theme.colors.light },

  monedaRow: { flexDirection: 'row', gap: 8 },
  monedaBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: Theme.radius.sm,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.surfaceAlt,
    alignItems: 'center',
  },
  monedaBtnActive: {
    borderColor: Theme.colors.primary,
    backgroundColor: Theme.colors.primary,
  },
  monedaBtnText: { fontSize: 13, fontWeight: '700', color: Theme.colors.muted },
  monedaBtnTextActive: { color: '#fff' },

  row: { flexDirection: 'row', gap: Theme.spacing.md, marginTop: 4 },
  halfField: { flex: 1 },
  fieldGroup: { marginBottom: Theme.spacing.md },

  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.surfaceAlt,
    borderRadius: Theme.radius.sm,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  itemDesc: { fontSize: 14, fontWeight: '600', color: Theme.colors.text },
  itemMeta: { fontSize: 12, color: Theme.colors.muted, marginTop: 2 },
  itemRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  itemTotal: { fontSize: 14, fontWeight: '700', color: Theme.colors.primary },
  itemDeleteBtn: { padding: 4 },

  addItemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: Theme.colors.primary,
    borderRadius: Theme.radius.md,
    borderStyle: 'dashed',
    paddingVertical: 13,
    marginTop: 4,
  },
  addItemText: { fontSize: 14, fontWeight: '600', color: Theme.colors.primary, marginLeft: 6 },

  totalCard: {
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.radius.md,
    paddingVertical: 18,
    paddingHorizontal: Theme.spacing.lg,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
    ...Theme.shadow.md,
  },
  totalCardLabel: { fontSize: 13, fontWeight: '700', color: 'rgba(255,255,255,0.8)', letterSpacing: 0.6 },
  totalCardValue: { fontSize: 22, fontWeight: '800', color: '#fff' },

  actionRow: { flexDirection: 'row', gap: Theme.spacing.md, marginTop: Theme.spacing.sm },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingVertical: 14,
    borderRadius: Theme.radius.md,
  },
  actionBtnOutline: {
    borderWidth: 1.5,
    borderColor: Theme.colors.primary,
    backgroundColor: Theme.colors.surface,
  },
  actionBtnSolid: {
    backgroundColor: Theme.colors.primary,
    ...Theme.shadow.md,
  },
  actionBtnOutlineText: { fontSize: 14, fontWeight: '700', color: Theme.colors.primary },
  actionBtnSolidText: { fontSize: 14, fontWeight: '700', color: '#fff' },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: {
    backgroundColor: Theme.colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: Theme.spacing.xl,
    paddingBottom: 36,
  },
  modalTitle: { fontSize: 16, fontWeight: '700', color: Theme.colors.text, marginBottom: Theme.spacing.lg },
  modalButtons: { flexDirection: 'row', gap: Theme.spacing.md, marginTop: Theme.spacing.lg },
  modalCancelBtn: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    alignItems: 'center',
  },
  modalAddBtn: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.primary,
    alignItems: 'center',
  },
  modalCancelText: { fontSize: 14, fontWeight: '600', color: Theme.colors.muted },
  modalAddText: { fontSize: 14, fontWeight: '600', color: '#fff' },

  clienteModal: {
    backgroundColor: Theme.colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: Theme.spacing.xl,
    maxHeight: '70%',
  },
  clienteModalTitle: { fontSize: 16, fontWeight: '700', color: Theme.colors.text, marginBottom: Theme.spacing.lg },
  clienteOption: { paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: Theme.colors.border },
  clienteOptionName: { fontSize: 14, fontWeight: '600', color: Theme.colors.text },
  clienteOptionEmpresa: { fontSize: 12, color: Theme.colors.muted, marginTop: 2 },
  emptyText: { color: Theme.colors.muted, textAlign: 'center', paddingVertical: 24 },
});
