import { StyleSheet } from 'react-native';
import Theme from '../constants/Theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  scroll: { padding: Theme.spacing.lg, paddingBottom: 60 },
  sectionCard: {
    backgroundColor: Theme.colors.surface, borderRadius: Theme.radius.md,
    padding: Theme.spacing.lg, marginBottom: Theme.spacing.lg, ...Theme.shadow.xs,
  },
  sectionTitle: { fontSize: 13, fontWeight: '700', color: Theme.colors.primary, textTransform: 'uppercase', letterSpacing: 0.4, marginBottom: Theme.spacing.md },
  fieldGroup: { marginBottom: Theme.spacing.md },
  label: { fontSize: 12, fontWeight: '600', color: Theme.colors.muted, textTransform: 'uppercase', letterSpacing: 0.3, marginBottom: 5 },
  input: {
    backgroundColor: Theme.colors.surfaceAlt, borderWidth: 1, borderColor: Theme.colors.border,
    borderRadius: Theme.radius.sm, paddingVertical: 10, paddingHorizontal: 12,
    fontSize: 14, color: Theme.colors.text,
  },
  textArea: { height: 70, textAlignVertical: 'top' },
  pickerButton: {
    backgroundColor: Theme.colors.surfaceAlt, borderWidth: 1, borderColor: Theme.colors.border,
    borderRadius: Theme.radius.sm, paddingVertical: 10, paddingHorizontal: 12,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
  },
  pickerButtonText: { fontSize: 14, color: Theme.colors.text },
  pickerButtonPlaceholder: { fontSize: 14, color: Theme.colors.light },
  row: { flexDirection: 'row', gap: Theme.spacing.md },
  halfField: { flex: 1 },
  itemRow: {
    backgroundColor: Theme.colors.surfaceAlt, borderRadius: Theme.radius.sm,
    padding: Theme.spacing.md, marginBottom: 8,
    borderWidth: 1, borderColor: Theme.colors.border,
  },
  itemDesc: { fontSize: 14, fontWeight: '600', color: Theme.colors.text, flex: 1 },
  itemMeta: { fontSize: 12, color: Theme.colors.muted, marginTop: 2 },
  itemTotal: { fontSize: 14, fontWeight: '700', color: Theme.colors.primary },
  addItemButton: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    borderWidth: 1.5, borderColor: Theme.colors.primary, borderRadius: Theme.radius.md,
    borderStyle: 'dashed', paddingVertical: 12, marginTop: 8,
  },
  addItemText: { fontSize: 14, fontWeight: '600', color: Theme.colors.primary, marginLeft: 6 },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 5 },
  totalLabel: { fontSize: 13, color: Theme.colors.muted },
  totalValue: { fontSize: 13, fontWeight: '600', color: Theme.colors.text },
  totalFinal: { flexDirection: 'row', justifyContent: 'space-between', paddingTop: 10, borderTopWidth: 1, borderTopColor: Theme.colors.border, marginTop: 4 },
  totalFinalLabel: { fontSize: 16, fontWeight: '700', color: Theme.colors.text },
  totalFinalValue: { fontSize: 18, fontWeight: '800', color: Theme.colors.primary },
  saveButton: {
    backgroundColor: Theme.colors.primary, borderRadius: Theme.radius.md,
    paddingVertical: 15, alignItems: 'center', marginTop: Theme.spacing.sm, ...Theme.shadow.md,
  },
  saveButtonText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: Theme.colors.surface, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: Theme.spacing.xl, paddingBottom: 32 },
  modalTitle: { fontSize: 16, fontWeight: '700', color: Theme.colors.text, marginBottom: Theme.spacing.lg },
  modalButtons: { flexDirection: 'row', gap: Theme.spacing.md, marginTop: Theme.spacing.md },
  modalCancelBtn: { flex: 1, paddingVertical: 12, borderRadius: Theme.radius.md, borderWidth: 1, borderColor: Theme.colors.border, alignItems: 'center' },
  modalAddBtn: { flex: 1, paddingVertical: 12, borderRadius: Theme.radius.md, backgroundColor: Theme.colors.primary, alignItems: 'center' },
  modalCancelText: { fontSize: 14, fontWeight: '600', color: Theme.colors.muted },
  modalAddText: { fontSize: 14, fontWeight: '600', color: '#fff' },
  clienteModal: { backgroundColor: Theme.colors.surface, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: Theme.spacing.xl, maxHeight: '70%' },
  clienteModalTitle: { fontSize: 16, fontWeight: '700', color: Theme.colors.text, marginBottom: Theme.spacing.lg },
  clienteOption: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Theme.colors.border },
  clienteOptionName: { fontSize: 14, fontWeight: '600', color: Theme.colors.text },
  clienteOptionEmpresa: { fontSize: 12, color: Theme.colors.muted },
});
